# Generated by Django 3.0.5 on 2021-05-04 14:47

from django.db import migrations, models
import djongo.models.fields
import rbcrypto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=200)),
                ('watchlist', djongo.models.fields.ArrayField(model_container=rbcrypto.models.Ticker)),
            ],
        ),
    ]
